MODEL:
  TRANSFORMER_TYPE: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0

  # HMA模块
  HMA_ENABLE: True
  FROZEN: True
  PRETRAIN_PATH_T: './pretrain/ViT-B-16.pt'
  NECK: 'bn'
  FLOPS_TEST: False
  ID_LOSS_TYPE: 'softmax'

  # CPE模块
  CPE_ENABLE: True
  CPE_LEARNABLE_AFFINITY: True
  CPE_START_LAYER: 6
  CPE_USE_CROSS_ATTN: True
  CPE_PROTO_POOLING: 'attn'
  CPE_MULTI_MODAL_FUSION: 'transformer'
  CPE_EVOLVE_TYPE: 'gru'
  CPE_FEEDBACK_PROTO: True
  CPE_LAYER_AGGR: True
  CPE_RETRIEVAL_FEAT: 'mlp'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 0

DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: './data'

SOLVER:
  BASE_LR: 0.00035
  HMA_LR_FACTOR: 1.5
  WARMUP_ITERS: 10
  MAX_EPOCHS: 50
  OPTIMIZER_NAME: 'Adam'
  IMS_PER_BATCH: 64
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './output'